SEARCH_RESULT_CARD = "[data-qa='vacancy-serp__vacancy']"
VACANCY_TITLE = "[data-qa='serp-item__title']"
VACANCY_TITLE_TEXT = "[data-qa='serp-item__title-text']"
COMPANY_NAME = "[data-qa='vacancy-serp__vacancy-employer-text']"
VACANCY_SNIPPET = "[data-qa='vacancy-serp__vacancy_snippet_responsibility'], [data-qa='vacancy-serp__vacancy_snippet_requirement']"
RESPONSE_BUTTON = "[data-qa='vacancy-response-link-top']"
VACANCY_DESCRIPTION = "[data-qa='vacancy-description'], .vacancy-description"
RESPONSE_TEXTAREA = "[data-qa='vacancy-response-popup-form-letter-input'], #cover-letter textarea, div[data-qa='textarea-native-wrapper'] textarea"
RESPONSE_SUBMIT_BUTTON = "[data-qa='vacancy-response-submit-popup'], [data-qa='vacancy-response-letter-submit']"
RESPONSE_ERROR_NOTIFICATION = "[data-qa='vacancy-response-error-notification']"
RELOCATION_CONFIRM_BUTTON = "[data-qa='relocation-warning-confirm']"
RESUME_DROPDOWN = "[data-qa='resume-title']"
RESUME_DOWNLOAD_BUTTON = '[data-qa="resume-download-button"]'
RESUME_TXT_EXPORT_LINK = "a[href*='resume_converter'][href*='type=txt']"
